### ISSUE TITLE
Crash from Get out of my sandbox

### ISSUE THREAD

**Issue by ZilgornZeypher** [SEServerExtender/GetOutOfMySandboxPlugin#1]
Exception occured: System.TypeLoadException: Could not load type 'SEModAPIInternal.API.Common.WorldSaveEventHandler' from assembly 'SEModAPIInternal, Version=1.76.11.412, Culture=neutral, PublicKeyToken=null'.
   at GetOutOfMySandbox.GetOutOfMySandbox.WaitLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by dodexahedron** [comment]
That's...an interesting one.
Have you encountered this more than once?

**Comment by ZilgornZeypher** [comment]
I encountered it 4 times. The first time crashed the server, the other 3 kept the server from loading sucessfully. I just removed the dll from the mod directory to allow the server to load.

**Comment by dodexahedron** [comment]
That indicates you are running an outdated version of SEServerExtender that doesn't support the functionality this plugin needs.
Please download the latest version of SEServerExtender.
