### ISSUE TITLE
Extender 1.83.8.489 with SE 1.083 - OOS 1.0.1.49

### ISSUE THREAD

**Issue by xxam** [SEServerExtender/GetOutOfMySandboxPlugin#3]
The plugin will not be loaded properly. Am i too quick and its going to be a new version vor sandboxplugin also?

**Comment by xxam** [comment]
Logfile shows:
2015-05-22 01:05:08.1925|Error|SEModAPIExtensions.API.PluginManager.InitPlugin|System.IO.FileLoadException: Could not load file or assembly 'NLog, Version=3.2.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'NLog, Version=3.2.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'
   at System.Signature.GetSignature(Void\* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at System.Reflection.RtFieldInfo.get_InvocationFlags()
   at System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at SEModAPIExtensions.API.PluginManager.InitPlugin(Guid key)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by dodexahedron** [comment]
An update for this will be released soon.

I neglected to actually upload the fixed version.

**Comment by xxam** [comment]
any news here?

**Comment by dodexahedron** [comment]
Updating this now.
